receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  attributes:
    actions:
      - key: service.name
        value: claude-code
        action: upsert
      - key: deployment.environment
        value: opencodeat
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: opencodeat
    const_labels:
      project: "opencodeat"
    
  logging:
    loglevel: info

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [logging]